<template>
  <div class="container">
    <div
      class="bg-text-container blur-card max-w-[1328px] py-[80px] px-[64px] rounded-[24px]"
    >
      <div>
        <h1><span>Terms</span> & Conditions</h1>
        <p class="text-[#C4C4C6] text-[18px] leading-[28px]">
          Last updated June 30, 2021.
        </p>
      </div>
      <div>
        <h2><span>Agreement</span> to terms</h2>
        <p>
          We are Termly Inc., doing business as Termly (“Termly,” “we,” “us,” or
          “our”), a company registered in the State of Delaware. We operate the
          website https://termly.io (the “Website”) through which we provide you
          our services, (collectively, the “Services” which include the
          provision and use of the Website).
          <br />
          <br />
          You can contact us by phone at (855) 234-5020, by email
          at info@termly.io, or by post to Termly Inc., 8 The Grn Ste B, Dover,
          DE 19901.
          <br />
          <br />
          These Terms of Use constitute a legally binding agreement made between
          you, whether personally or on behalf of an entity (“you”) and
          concerning your access to and use of the Website and the Services. You
          agree that by accessing the Services, you have read, understood, and
          agree to be bound by all of these Terms of Use. IF YOU DO NOT AGREE
          WITH ALL OF THESE TERMS OF USE, THEN YOU ARE EXPRESSLY PROHIBITED FROM
          USING THE SERVICES AND YOU MUST DISCONTINUE USE IMMEDIATELY.
          <br />
          <br />
          Supplemental terms and conditions or documents that may be posted on
          the Website from time to time are hereby expressly incorporated herein
          by reference. We reserve the right, in Termly’s sole discretion, to
          make changes or modifications to these Terms of Use from time to time.
          We will alert you about any changes by updating the “Last updated”
          date of these Terms of Use, and you waive any right to receive
          specific notice of each such change. It is your responsibility to
          periodically review these Terms of Use to stay informed as each time
          you access the Services, you will be subject to, and will be deemed to
          have been made aware of and to have accepted, the then applicable
          Terms of Use.
          <br />
          <br />
          The Services are intended for business users who are at least 18 years
          old. Persons under the age of 18 are not permitted to use or register
          for the Services.
        </p>
      </div>
      <div>
        <h2><span>1. Website</span>& Services</h2>
        <p>
          We are not lawyers nor a law firm, but we help you with compliance in
          relation to your privacy and contractual obligations. We provide you a
          software (the “Software”), that you access remotely via the cloud,
          that you can use for (a) consent management (“Consent Platform”); and
          (b) the generation of policies, legal agreements, disclaimers, and
          other documents generated by the Services using information related to
          your business or organization that you enter into the Software
          (collectively “Forms”).
          <br />
          <br />
          The information, Consent Platform, and Forms provided when using the
          Services are not intended for distribution to or use by any person or
          entity in any jurisdiction or country where such distribution or use
          would be contrary to law or regulation or which would subject us to
          any registration requirement within such jurisdiction or country.
          Accordingly, those persons who choose to access the Services from
          other locations do so on their own initiative and are solely
          responsible for compliance with local laws, if and to the extent local
          laws are applicable.
          <br />
          <br />
          The Services are not tailored to comply with industry-specific
          regulations (including Health Insurance Portability and Accountability
          Act (HIPAA), Federal Information Security Management Act (FISMA),
          etc.), so if your interactions would be subjected to such laws, you
          may not use these Services. You may not use the Services in a way that
          would violate the Gramm-Leach-Bliley Act (GLBA).
        </p>
        <h3><span> Using </span>Forms</h3>
        <p>
          You may use any Forms generated by the Software through your use of
          our generator(s) for your business or organization. It is your
          responsibility to determine whether the Forms generated by the
          Software are appropriate for your use. From time to time, we may
          notify you that a particular Form may need to be updated in response
          to changes in applicable laws or other guidance, rules or regulations,
          and you are responsible for determining whether to update the Forms
          used in your business or organization.<br />
          <br />
          WE DO NOT REPRESENT THAT THE FORMS WILL MEET YOUR SPECIFIC GOALS,
          PROTECT YOUR SPECIFIC INTERESTS, OR WITHSTAND CHALLENGES TO THEIR
          LEGAL OR FACTUAL SUFFICIENCY. THE FORMS ARE NOT PROVIDED WITH ANY
          GUARANTY, WARRANTY, OR REPRESENTATION AS TO QUALITY OR SUITABILITY FOR
          ANY PARTICULAR PURPOSE. The Forms are general in nature and may not be
          sufficient to protect you against a specific risk, problem or dispute.
          Our software’s generation of a Form does not constitute the practice
          of law and is not legal counsel or advice. You should not rely on a
          Form as a substitute for consultation with an attorney.
        </p>
      </div>
      <div>
        <h2><span>2. Intellectual</span>Property Rights</h2>
        <p>
          We are not lawyers nor a law firm, but we help you with compliance in
          relation to your privacy and contractual obligations. We provide you a
          software (the “Software”), that you access remotely via the cloud,
          that you can use for (a) consent management (“Consent Platform”); and
          (b) the generation of policies, legal agreements, disclaimers, and
          other documents generated by the Services using information related to
          your business or organization that you enter into the Software
          (collectively “Forms”).
          <br />
          <br />
          The information, Consent Platform, and Forms provided when using the
          Services are not intended for distribution to or use by any person or
          entity in any jurisdiction or country where such distribution or use
          would be contrary to law or regulation or which would subject us to
          any registration requirement within such jurisdiction or country.
          Accordingly, those persons who choose to access the Services from
          other locations do so on their own initiative and are solely
          responsible for compliance with local laws, if and to the extent local
          laws are applicable.
          <br />
          <br />
          The Services are not tailored to comply with industry-specific
          regulations (including Health Insurance Portability and Accountability
          Act (HIPAA), Federal Information Security Management Act (FISMA),
          etc.), so if your interactions would be subjected to such laws, you
          may not use these Services. You may not use the Services in a way that
          would violate the Gramm-Leach-Bliley Act (GLBA).
        </p>
      </div>
    </div>
  </div>
</template>

<script></script>

<style></style>
